### ISSUE TITLE
You mention Mutual information but I find the correlation in code

### ISSUE THREAD

**Issue by chengyu89527** [Healingl/BMCAN#1]
Can you explain why the demo is about correlation ,but you mention mutual information.  Do you also use the MI method in contrastive learning?

**Comment by Healingl** [comment]
> Can you explain why the demo is about correlation ,but you mention mutual information. Do you also use the MI method in contrastive learning?

You can see the PatchNCE loss of patchnce.py for maximizing the mutual information between the same location of input and output images.

**Comment by chengyu89527** [comment]
Thanks for replay, Do yuo mean the mutual information you mentioned is just between the patches instead of whole images ? Is the correlation useless in this case ?
&nbsp;


成大宇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月20日(星期一) 下午3:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Healingl/BMCAN] You mention Mutual information but I find the correlation in code (Issue #1)





  
Can you explain why the demo is about correlation ,but you mention mutual information. Do you also use the MI method in contrastive learning?
  
You can see the PatchNCE loss of patchnce.py for maximizing the mutual information between the same location of input and output images.

**Comment by Healingl** [comment]
> 
The PatchNCE loss is used in bidirectional contrastive learning for maximizing the mutual information of image patches (represented by encoding features) in the feature space, and the anatomical structure consistency with correlation coefficient is used to enhance the structural consistency between real and fake images in the pixel space.

**Comment by chengyu89527** [comment]
Thanks!!!!! I understand now. Last two qeustions ?Is there the different between this mehtod and "Contrastive Learning for Unpaired Image-to-Image Translation"? what's resolution of MINDLoss()'s input,can I directly put img and syn instead?
&nbsp;


成大宇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月20日(星期一) 下午3:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Healingl/BMCAN] You mention Mutual information but I find the correlation in code (Issue #1)





   
The PatchNCE loss is used in bidirectional contrastive learning for maximizing the mutual information of image patches (represented by encoding features) in the feature space, and the anatomical structure consistency with correlation coefficient is used to enhance the structural consistency between real and fake images in the pixel space.
